### ISSUE TITLE
core-js@<2.6.5 is no longer maintained

### ISSUE THREAD

**Issue by joma74** [DevExpress/testcafe-browser-tools#167]
On upgrading testcafe to 1.1.3, yarn logs `warning testcafe > testcafe-browser-tools > babel-runtime > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to co
re-js@3 or at least to actual version of core-js@2.`

- "testcafe@1.1.3" states "testcafe-browser-tools": "1.6.8", traced to resolve to "1.6.8"
- "testcafe-browser-tools" states "babel-runtime": "^5.6.15", traced to resolve to "5.8.38".
- "babel-runtime" states "core-js": "^1.0.0", traced to resolve to "1.2.7"
- https://www.npmjs.com/package/core-js/v/1.2.7 displays depercation warning

**Comment by miherlosev** [comment]
Hi @joma74 

Thank you for your remark. We will think what we can do with it.

**Comment by fmancardi** [comment]
Hi same today
npm -g install testcafe
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/testcafe -> /usr/local/lib/node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/testcafe/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

**Comment by AlexSkorkin** [comment]
Thank you for your input. We will take it into account when looking into this issue.

**Comment by ThorstenBux** [comment]
Hi @AlexSkorkin any update on this?

**Comment by AlexSkorkin** [comment]
Once we get any results, we will share them here.

**Comment by jzhang52** [comment]
Hi, we ran into the same issue when installing testcafe 1.9.1
`npm : npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

Hope you could resolve this some time soon. Thanks!

**Comment by carolord999** [comment]
Hi, I still have the issue. 
Then I tried to update using : npm i -g core-js@^3
But every times I go back to : npm install -g testcafe 
I get the error.

**Comment by miherlosev** [comment]
Hi @carolord999

TestCafe uses `core-js@2.x` internally as a `Babel@6` dependency. This message will be always displayed when TestCafe uses this dependency.
Now, we are starting to update all TestCafe related modules up to Babel@7 and, in the future, this message will not be shown.
Note that the displayed message is a warning and it doesn't break the TestCafe functionality.

Stay tuned to [https://github.com/DevExpress/testcafe/issues/3425](https://github.com/DevExpress/testcafe/issues/3425) to be informed about our progress.

**Comment by AndreyBelym** [comment]
Closing this since DevExpress/testcafe#3425 is closed and `testcafe-browser-tools` uses TypeScript now.
