### ISSUE TITLE
Test failing for browser tool related issue: ERROR NativeBinaryHasFailedError: The find-window process failed with the 1 exit code.

### ISSUE THREAD

**Issue by davilo61** [DevExpress/testcafe-browser-tools#221]
I'm unable to run a test on a MacBook Pro running Monterrey v12.1 I get the below error. I tried the following:
1. tccutil reset ScreenCapture com.devexpress.testcafe-browser-tools
2. tccutil reset AppleEvents com.devexpress.testcafe-browser-tools
3. npm install testcafe-browser-tools

...Run `npm audit` for details
administrator@adminisatorsMBP jobnetwork_testcafe_poc % testcafe
Using locally installed version of TestCafe.
ERROR NativeBinaryHasFailedError: The find-window process failed with the 1 exit code.
Process output:
The application /Users/administrator/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/MacOS/testcafe-browser-tools cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002fe03f0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
    at ChildProcess.<anonymous> (/Users/administrator/Documents/jobnetwork_testcafe_poc/node_modules/testcafe/node_modules/testcafe-browser-tools/src/utils/exec.js:74:24)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by AlexanderMoiseev** [comment]
Hi, 

Try removing the .testcafe-browser-tools folder from your home directory. If this does not help, try executing the following command:

`chmod +x "/Users/{user}/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/MacOS/testcafe-browser-tools"`

Also, if you are using the M1 chip, try installing Rosetta 2. If the problem still persists, add a sample project and a video to demonstrate how you reproduce the issue. Make sure that the callstack with the problem is also visible.

**Comment by davilo61** [comment]
Thanks for your response. I had tried removing the browser tools folder, but the issue persisted. However, exe the chmod +x cmd recommended above seemed to resolve that error.
